name: Docker CICD

on: [push, workflow_dispatch,pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag 590733205684.dkr.ecr.me-central-1.amazonaws.com/nextjs


    - name: Install and configure AWS CLI
      run: |
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip -q awscliv2.zip
            sudo ./aws/install --update
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws configure set default.region me-central-1

    - name: Login to ECR
      run: |
            aws ecr get-login-password --region me-central-1 | docker login --username AWS --password-stdin 590733205684.dkr.ecr.me-central-1.amazonaws.com

    - name: Tag and push Docker image
      run: |
            docker tag 590733205684.dkr.ecr.me-central-1.amazonaws.com/nextjs:latest 590733205684.dkr.ecr.me-central-1.amazonaws.com/nextjs
            docker push 590733205684.dkr.ecr.me-central-1.amazonaws.com/nextjs

            
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - name: pull image from AWS ECR
      run: docker push 590733205684.dkr.ecr.me-central-1.amazonaws.com/nextjs:${GITHUB_SHA}
    - name: run docker container
      run: docker run -d -p 3000:3000 --name nextjs 590733205684.dkr.ecr.me-central-1.amazonaws.com/nextjs
